<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="xunit" Version="2.6.4" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HardenLabs.Hmac\HardenLabs.Hmac.csproj" />
    <ProjectReference Include="..\HardenLabs.Hmac.AspNetCore\HardenLabs.Hmac.AspNetCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\tests\cross-language\test-vectors.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>test-vectors.json</Link>
    </Content>
  </ItemGroup>

</Project>
